# Define absolute paths to data pipeline files.

paths:
  pipeline_log_file: "/solar-forecasting/logs/pipeline_log.csv"
  data_download_file: "/solar-forecasting/app/pipeline/sharp_metadata_dump.csv"
  scaler_file: "/solar-forecasting/app/pipeline/scaler.pkl"
  data_pipeline_file: "/solar-forecasting/app/pipeline/data_feed.pt"
  model_weights_file: "/solar-forecasting/models/best_model_v2.pt"
  forecast_file: "/solar-forecasting/app/pipeline/forecast.json"
  database_file: "/solar-forecasting/app/database/app.db"
  database_schema: "/solar-forecasting/app/database/schema.sql"
  intensity_classifier: "/solar-forecasting/app/pipeline/intensity_class.json"
